/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6/userguide/multi_project_builds.html
 */

rootProject.name = "asteroidos-link"

include(":asteroidos-link")
include(":testApp")

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    // Using PREFER_PROJECT for the Native target, which imports the "ivy" repository.
    // See: https://stackoverflow.com/a/75032841/560774
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        google()
        mavenCentral()
    }
    versionCatalogs {
        create("libs") {
            version("kotlin", "1.8.0")
            version("ktlint", "11.0.0")
            version("kotlinx-coroutines", "1.6.4")
            version("kotlinx-datetime", "0.4.0")
            version("android-gradle", "7.4.0")
            version("androidx-core-ktx", "1.9.0")
            version("nordic-ble", "2.6.0")

            plugin("ktlint", "org.jlleitschuh.gradle.ktlint").versionRef("ktlint")
            plugin("android-library", "com.android.library").versionRef("android-gradle")
            plugin("android-application", "com.android.application").versionRef("android-gradle")

            library("kotlinx-coroutines-core", "org.jetbrains.kotlinx", "kotlinx-coroutines-core").versionRef("kotlinx-coroutines")
            library("kotlinx-datetime", "org.jetbrains.kotlinx", "kotlinx-datetime").versionRef("kotlinx-datetime")

            library("androidx-core", "androidx.core", "core-ktx").versionRef("androidx-core-ktx")

            library("nordic-ble-common", "no.nordicsemi.android", "ble-common").versionRef("nordic-ble")
            library("nordic-ble-ktx", "no.nordicsemi.android", "ble-ktx").versionRef("nordic-ble")
        }

        create("testAppLibs") {
            version("androidx-lifecycle-runtime-ktx", "2.5.1")
            version("androidx-activity", "1.6.1")
            version("androidx-navigation", "2.5.3")
            version("compose-ui", "1.3.3")
            version("compose-material", "1.3.1")
            version("compose-foundation", "1.3.1")

            library("androidx-lifecycle", "androidx.lifecycle", "lifecycle-runtime-ktx").versionRef("androidx-lifecycle-runtime-ktx")
            library("androidx-activity", "androidx.activity", "activity-ktx").versionRef("androidx-activity")
            library("androidx-activity-compose", "androidx.activity", "activity-compose").versionRef("androidx-activity")
            library("androidx-compose-ui", "androidx.compose.ui", "ui").versionRef("compose-ui")
            library("androidx-compose-ui-tooling", "androidx.compose.ui", "ui-tooling").versionRef("compose-ui")
            library("androidx-compose-material", "androidx.compose.material", "material").versionRef("compose-material")
            library("androidx-compose-foundation", "androidx.compose.foundation", "foundation").versionRef("compose-foundation")
            library("androidx-navigation-runtime", "androidx.navigation", "navigation-runtime-ktx").versionRef("androidx-navigation")
            library("androidx-navigation-compose", "androidx.navigation", "navigation-compose").versionRef("androidx-navigation")
        }
    }
}
